### ISSUE TITLE
Error de servidor en el componente "propuestas"

### ISSUE THREAD

**Issue by f-solera** [openpoke/decidim-inclusiva#2]
Al entrar en la siguiente url:
[https://decidimoseducacioninclusiva.uma.es/processes/Proyecto-QeC-Latinoamerica/f/42/proposals](https://decidimoseducacioninclusiva.uma.es/processes/Proyecto-QeC-Latinoamerica/f/42/proposals)

Me aparece el siguiente error:
"**Ha habido un problema con nuestro servidor**
Inténtalo de nuevo más tarde. Si el error persiste, por favor 
copia la siguiente información y envíala a las mantenedoras de la 
plataforma con cualquier otra información que quieras compartir.

ID de participante | 3
-- | --
2024-09-26T10:36:12.923680
GET
https://decidimoseducacioninclusiva.uma.es/processes/Proyecto-QeC-Latinoamerica/f/42/proposals
[a2eef802-fd3f-4859-bf76-ec517be14478]"

Puedo acceder a las propuestas de manera individual, entrando en sus enlaces, pero no a la página que las agrupa.

**Comment by paarals** [comment]
solucionado actualizando las versiones: https://github.com/openpoke/decidim-inclusiva/commit/bf5e62eee0a22ca94befa09e7e3ba1848ac1ccda
